steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sish:$SHORT_SHA', '.' ]
  id: 'build-sish'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ "$BRANCH_NAME" == "master" ]]; then
      docker tag gcr.io/$PROJECT_ID/sish:$SHORT_SHA gcr.io/$PROJECT_ID/sish
      docker push gcr.io/$PROJECT_ID/sish
    else
      exit 0
  wait_for: ['build-sish']
  id: 'latest'
images:
- 'gcr.io/$PROJECT_ID/sish:$SHORT_SHA'