steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sish:$SHORT_SHA', '.' ]
  id: 'build-sish'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && docker tag gcr.io/$PROJECT_ID/sish:$SHORT_SHA gcr.io/$PROJECT_ID/sish
  wait_for: ['build-sish']
  id: 'latest'
images:
- 'gcr.io/$PROJECT_ID/sish:latest'
- 'gcr.io/$PROJECT_ID/sish:$SHORT_SHA'