admin-console: false
admin-console-token: ""
alias-load-balancer: false
append-user-to-subdomain: false
append-user-to-subdomain-separator: '-'
authentication: true
authentication-key-request-timeout: 5s
authentication-key-request-url: ""
authentication-keys-directory: deploy/pubkeys/
authentication-keys-directory-watch-interval: 200ms
authentication-password: ""
banned-aliases: ""
banned-countries: ""
banned-ips: ""
banned-subdomains: localhost
bind-any-host: false
bind-hosts: ""
bind-http-auth: true
bind-http-path: true
bind-random-aliases: true
bind-random-aliases-length: 3
bind-random-ports: true
bind-random-subdomains: true
bind-random-subdomains-length: 3
bind-root-domain: false
bind-wildcards: false
cleanup-unauthed: true
cleanup-unauthed-timeout: 5s
cleanup-unbound: false
cleanup-unbound-timeout: 5s
config: config.yml
debug: false
debug-interval: 2s
domain: ssi.sh
force-all-https: false
force-https: false
force-requested-aliases: false
force-requested-ports: false
force-requested-subdomains: false
force-tcp-address: false
geodb: false
http-address: localhost:80
http-load-balancer: false
http-port-override: 0
http-request-port-override: 0
https: false
https-address: localhost:443
https-certificate-directory: deploy/ssl/
https-certificate-directory-watch-interval: 200ms
https-ondemand-certificate: false
https-ondemand-certificate-accept-terms: false
https-ondemand-certificate-email: ""
https-port-override: 0
https-request-port-override: 0
idle-connection: true
idle-connection-timeout: 5s
load-templates: true
load-templates-directory: templates/*
localhost-as-all: true
log-to-client: false
log-to-file: false
log-to-file-compress: false
log-to-file-max-age: 28
log-to-file-max-backups: 3
log-to-file-max-size: 500
log-to-file-path: /tmp/sish.log
log-to-stdout: true
ping-client: true
ping-client-interval: 5s
ping-client-timeout: 5s
port-bind-range: 0,1024-65535
private-key-passphrase: S3Cr3tP4$$phrAsE
private-keys-directory: deploy/keys
proxy-protocol: false
proxy-protocol-listener: false
proxy-protocol-policy: use
proxy-protocol-timeout: 200ms
proxy-protocol-use-timeout: false
proxy-protocol-version: "1"
redirect-root: true
redirect-root-location: https://github.com/antoniomika/sish
rewrite-host-header: true
service-console: false
service-console-max-content-length: -1
service-console-token: ""
sni-load-balancer: false
sni-proxy: false
sni-proxy-https: false
ssh-address: localhost:2222
strip-http-path: true
tcp-address: ""
tcp-aliases: false
tcp-aliases-allowed-users: false
tcp-load-balancer: false
time-format: 2006/01/02 - 15:04:05
verify-dns: true
verify-ssl: true
whitelisted-countries: ""
whitelisted-ips: ""
