name: Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint the codebase
      run: |
        docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.27.0 golangci-lint run -E goimports
    - name: Build and the Docker images
      run: |
        DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

        docker build \
          --cache-from ${GITHUB_REPOSITORY}-cache \
          --build-arg VERSION=${GITHUB_SHA} \
          --build-arg COMMIT=${GITHUB_SHA} \
          --build-arg DATE=${DATE} \
          -t ${GITHUB_REPOSITORY}:${GITHUB_SHA} .
